name: Tests

on:
  push:
    branches:
      - test

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Start test services
        run: docker compose up -d --build
        working-directory: test

      - name: Show logs if failed
        if: failure()
        run: docker compose logs
        working-directory: test

      - name: Stop test services
        if: always()
        run: docker compose down -v
        working-directory: test

  publish-report:
    if: always()
    needs: [run-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Check out gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report with history
        uses: simple-elf/allure-report-action@v1.13
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history